### ISSUE TITLE
Add import possibility

### ISSUE THREAD

**Issue by sevenflip** [koninklijke-collective/my_redirects#72]
If I want to create a bunch of redirects, I cannot do this simply via the DB, because the url_hash is generated with non-existing SQL functions (for example urlencoding of query parts).
Either there should be a "add missing url_hash'es" task (so I can add directly to the DB and recalculate the missing hashes via scheduler), or a import-possibility for CSV files or related.

What do you think about this?

**Comment by bmoex** [comment]
Hi @sevenflip, 

If you are still running the 3.x version, its available. (see the extension update script) 
However, I just verified, this is missing in version 4.x, since most were moved to the Install tool Update scripts.

Will create a simple install tool update function to calculate the required fields and hashes. 

Thanks for your report.
